version: 0.2

env:
  image: aws/codebuild/standard:7.0

phases:
  install:
    commands:
      - echo "=== Installing build dependencies ==="
      - apt-get update
      - apt-get install -y zip

  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      - echo "Current directory: $(pwd)"
      - echo "Directory contents:"
      - ls -la

  build:
    commands:
      - echo "=== Building application ==="
      - echo "Static HTML - no build process needed"

  post_build:
    commands:
      - echo "=== Post-build phase ==="
      - echo "Build completed on $(date)"
      - echo "Creating deployment archive..."
      - zip -r deployment.zip . -x "*.git*" "*.github*" "*.DS_Store"
      - echo "Build artifacts prepared"

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no
