version: 0.2

env:
  image: aws/codebuild/standard:7.0

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y zip

  build:
    commands:
      - echo "Building the application..."
      - echo "No build commands needed for static HTML"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Creating deployment package..."
      - zip -r deployment-package.zip . -x "*.git*" "*.github*"

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no
