version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update

  build:
    commands:
      - echo "Building the application..."
      - echo "No build commands needed for static HTML"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Creating deployment package..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
